name: nginx.proxy

networks:
 kong:
  driver: bridge
  name: kong-net 

services:
  nginx:
    container_name: nginx-proxy
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - kong
    ports:
      - 80:80
      - 443:443

    restart: always
    labels:
      - "ningx.proxy"
      - "nginx"