name: nginx.proxy

networks:
 kong:
  driver: bridge
  name: kong-net 

services:
  nginx:
    container_name: nginx-proxy
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - kong
    ports:
      - 80:80
      - 443:443

    restart: always
    labels:
      - "ningx.proxy"
      - "nginx"

  certbot:
    image: certbot/dns-cloudflare:latest
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-varlib:/var/lib/letsencrypt
      - ./nginx/html:/var/www/html
      - ./cloudflare.ini:/cloudflare.ini
    environment:
      - CERTBOT_EMAIL=collinkleest@gmail.com
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $!; done'"
    networks:
      - kong
  
volumes:
  certbot-etc:
  certbot-varlib: