# .github/workflows/ci.yaml

name: Validate NGINX Config

on:
  push:
    branches:
        - master
  pull_request:
    branches:
        - master
        

jobs:
  validate-nginx:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Test NGINX configuration
      run: |
        docker run --rm -v ${{ github.workspace }}/nginx.conf:/etc/nginx/conf.d/default.conf nginx:latest nginx -t
    
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nginx-custom:latest .

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
  
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
  
        # Build and push the Docker image to Docker Hub
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx.proxy:latest