# .github/workflows/release.yaml

name: nginx.proxy release

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Start Application
        uses: collinkleest/remote-release@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
