# .github/workflows/release.yaml

name: nginx.proxy release

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Start Application
        uses: collinkleest/remote-release@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          command: |
            rm cloudflare.ini
            echo dns_cloudflare_email = ${{ secrets.CLOUDFLARE_EMAIL }} >> cloudflare.ini
            echo dns_cloudflare_api_key = ${{ secrets.CLOUDFLARE_API_KEY }} >> cloudflare.ini
            chmod 600 cloudflare.ini
            docker compose down
            docker compose up -d
