# .github/workflows/renew-certificates.yaml

name: rewew letsencrypt certificates

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Start Application
        uses: collinkleest/remote-release@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          command: |
            sudo certbot certonly \
              --dns-cloudflare \
              --dns-cloudflare-credentials cloudflare.ini \
              -d "*.betlab.app" -d "betlab.app" -d "*.collinkleest.com" -d "collinkleest.com" \
              -d "api.liteproxy.collinkleest.com" \
              --email collinkleest@gmail.com --agree-tos --non-interactive
