# .github/workflows/schedule-cron.yaml

name: schedule renewal cron

on:
  workflow_dispatch:

jobs:
  schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Start Application
        uses: collinkleest/remote-release@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          command: |
            CRON_JOB="*/1 * * * * echo "${{ secrets.PASSWORD }}" | sudo -S certbot certonly \
              --dns-cloudflare \
              --dns-cloudflare-credentials cloudflare.ini \
              -d "*.betlab.app" -d "betlab.app" -d "*.collinkleest.com" -d "collinkleest.com" \
              -d "api.liteproxy.collinkleest.com" \
              --email collinkleest@gmail.com --agree-tos --non-interactive"
            (crontab -l | grep -F "$CRON_JOB") || (crontab -l; echo "$CRON_JOB") | crontab -
                